### ISSUE TITLE
Question: Which file are the driver settings read from

### ISSUE THREAD

**Issue by Consti10** [svpcom/rtl8812au#19]
Hello,
I cannot figure it out myself, which file does this driver read its extra options(like `rtw_tx_pwr_idx_override`) from ?

E.g. how should you name the file under `/etc/modprobe.d/` .

Also, any way to just log the value to make sure in the driver ?

I am experimenting around here:
https://github.com/OpenHD/rtl8812au-5.2.20/commit/cdbe62fd9f99dd5ef90cbba590bbb71ebe7a84b7

**Comment by svpcom** [comment]
File name could be any, but you need to specify correct module name inside:
```
options 88XXau_wfb rtw_tx_pwr_idx_override=58
```

**Comment by Consti10** [comment]
thanks
