### ISSUE TITLE
Difference between this repo and others?

### ISSUE THREAD

**Issue by tech4him1** [svpcom/rtl8812au#2]
Is there any intentional use case or difference between this repo, aircrack-ng/rtl8812au, gordboy/rtl8812au, etc? Thanks!

**Comment by svpcom** [comment]
This repo intended to use with https://github.com/svpcom/wifibroadcast. It has minimal set of changes around original Realtek drivers to be compatible with WFB.

**Comment by tech4him1** [comment]
Thank you! Where are the original Realtek drivers sourced from?

**Comment by svpcom** [comment]
From tar.gz files provided by OEM with various cards on rtl88xx chipset.
