### ISSUE TITLE
Activating External Amplifier on RTL8812AU Using TRSW-S0 and TRSW-S1

### ISSUE THREAD

**Issue by daniel-yavorovich** [svpcom/rtl8812au#38]
The goal is to activate an external power amplifier connected to the RTL8812AU via the TRSW-S0 and TRSW-S1 pins. The current driver implementation needs modifications to control these pins for enabling the amplifier. Specifically, I need insights into the required GPIO configurations and register manipulations for proper control of the PA_EN signal through TRSW-S0 and TRSW-S1. Any previous experiences or examples related to this configuration would be helpful.

**Comment by svpcom** [comment]
I think only Realtek could help, because datasheet about internal card registers is not public available
