### ISSUE TITLE
Driver Fails to be installed on nv_nano

### ISSUE THREAD

**Issue by gyillikci** [svpcom/rtl8812au#8]
Hello Vasily,

Thanks for the repo firstly,

I am struggling to make the driver work on jetson nano.I modiefed the Makefile as:

`CONFIG_PLATFORM_I386_PC = n
.
.
.
CONFIG_PLATFORM_ARM_NV_NANO = y`
and installed it by sudo make install.

when I plug the AC56 and dmesg, i see that the driver is already registered seen below:
` 6.314813] iwlwifi 0000:01:00.0: Falling back to user helper
[    6.328989] usbcore: registered new interface driver rtl8812au
[    6.399248] 8812au: loading out-of-tree module taints kernel.
[    6.467905] RTL871X: module init start
[    6.467910] RTL871X: rtl8812au v4.3.8_12175.20140902
[    6.467913] RTL871X: build time: Jun 20 2021 16:20:41
[    6.467931] Error: Driver 'rtl8812au' is already registered, aborting...
[    6.474810] RTL871X: module init ret=-16
[    6.806752] usbcore: registered new interface driver rtl88XXau
[    6.819857] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-24.uc`

On jetson, there are two kernels:
`4.15.0-144-generic  4.9.201-tegra`

My problem is  when I run `sudo iw dev wlan0 set type monitor` I get `command failed: Operation not supported (-95)
`
I am not sure how the driver mechanism works but, couldnt find out the cause. Can you help on this issue?

Best,

Giray

**Comment by svpcom** [comment]
```
rtl8812au v4.3.8_12175.20140902
```
It seems that old driver already loaded. Try to do `find /lib/modules -name 8812` or `find /lib/modules -iname 88XX`, remove them and rebuild initramfs
